name: Update Starred Repos
on:
  schedule:
    # 每天0点运行
    - cron: "0 0 * * *"
  # 也可以手动触发
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install axios
      - name: Run fetch script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node scripts/fetchStars.js
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update starred repos" && git push origin main)
